name: seq
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - pyyaml
  - matplotlib
  - numpy
  - pandas
  - plotly
  - scipy
  - seaborn
  - statsmodels
  - ipykernel
  - pyyaml
  - h5py
  - pytables
